this.FishGrammer = tracery.createGrammar({
  PronounSing: ["It", "He", "She"], // singular — use with verb + s
  PronounPlur: ["They"], // plural — use with base verb
  Pronouns2: ["Its", "Their", "His", "Her"],
  moveSing: ["flocks", "races", "glides", "dances", "flees", "drifts"],
  movePlur: ["flock", "race", "glide", "dance", "flee", "drift"],
  bird: ["swan", "heron", "sparrow", "swallow", "wren", "robin"],
  animal: ["#bird#", "turtle", "banana slug", "panda", "bull", "worm"],
  specimen: [
    "dreamer",
    "specimen",
    "trickster",
    "opportunist",
    "oddity",
    "witty fish",
    "laid-back fish",
    "hungry fish",
    "prankster",
    "derpy fish",
  ],
  agent: ["cloud", "wave", "#bird#", "boat", "ship"],
  compass: ["Western", "Eastern", "Southern", "Northern"],
  location: [
    "American ",
    "Asian ",
    "European ",
    "Middle-Eastern ",
    "",
    "Antarctic ",
    "African ",
    "#compass# ",
    "Alaskan ",
  ],
  transVerbSing: [
    "forgets",
    "plants",
    "greets",
    "remembers",
    "embraces",
    "feels",
    "loves",
  ],
  transVerbPlur: [
    "forget",
    "plant",
    "greet",
    "remember",
    "embrace",
    "feel",
    "love",
  ],
  transVerbed: [
    "forgotten",
    "planted",
    "greeted",
    "remembered",
    "embraced",
    "felt",
    "loved",
  ], // proper past tense
  doThingSing: ["comes", "moves", "cries", "weeps", "laughs", "dreams"],
  doThingPlur: ["come", "move", "cry", "weep", "laugh", "dream"],
  emotion: [
    // adjectives "lost" and "empty" removed
    "sorrow",
    "gladness",
    "joy",
    "heartache",
    "love",
    "forgiveness",
    "grace",
    "longing",
    "wonder",
  ],
  substance: [
    "#emotion#",
    "mist",
    "fog",
    "glass",
    "silver",
    "rain",
    "dew",
    "cloud",
    "virtue",
    "sun",
    "shadow",
    "gold",
    "light",
    "darkness",
    "dad",
  ],
  adj: [
    "fair",
    "bright",
    "splendid",
    "divine",
    "fine",
    "lazy",
    "grand",
    "slow",
    "quick",
    "graceful",
    "grave",
    "clear",
    "faint",
    "dreary",
  ],
  verb: [
    "fleck",
    "grace",
    "bless",
    "dapple",
    "touch",
    "caress",
    "smooth",
    "crown",
    "veil",
  ],
  verbed: [
    "flecked",
    "graced",
    "blessed",
    "dappled",
    "touched",
    "caressed",
    "smoothed",
    "crowned",
    "veiled",
    "shaded",
    "unleashed",
  ],
  ground: [
    "glen",
    "river",
    "vale",
    "sea",
    "meadow",
    "forest",
    "glade",
    "grass",
    "sky",
    "waves",
  ],
  poeticAdj: ["#substance#-#verbed#"],
  poeticDesc: [
    "#poeticAdj#",
    "#adj# with #substance#",
    "#verbed# with #substance#",
  ],
  on: ["on", "in", "above", "beneath", "under", "by", "within"],
  noun: ["#ground#", "#agent#"],
  fishtypes: [
    "Salmon",
    "Trout",
    "SeaBear",
    "Guppy",
    "Minnow",
    "Angelfish",
    "Tetra",
    "Queenfish",
    "Catfish",
    "Needlefish",
    "Sunfish",
    "Danio",
    "Sturgeon",
    "Snapper",
  ],
  fishName: [
    "#location##verbed# #ground# #fishtypes#",
    "#location##emotion# #fishtypes#",
    "#location##animal# #fishtypes#",
    "#location##agent# #fishtypes#",
    "#location##substance# #fishtypes#",
  ],
  Description: [
    // singular pronoun + verb-s
    "#PronounSing# #moveSing# through #verbed# #ground#, lost in #emotion#.",
    "#PronounSing# #doThingSing# like a #animal# #on# the #ground#.",
    "#PronounSing# #moveSing# #on# the #ground#, full of #emotion#.",
    "#PronounSing# #transVerbSing# the #ground# like no other.",
    "#PronounSing# is #adj# and full of #emotion#.",
    "#PronounSing# has never #transVerbed# #Pronouns2# #emotion#, and it shows.",
    // plural pronoun + base verb
    "#PronounPlur# #movePlur# through #verbed# #ground#, lost in #emotion#.",
    "#PronounPlur# #doThingPlur# like a #animal# #on# the #ground#.",
    "#PronounPlur# #transVerbPlur# the #ground# like no other.",
    // pronoun-free (always safe)
    "A #adj# #specimen# that #doThingSing# of #emotion#.",
    "A #specimen# on a mission to find #substance#.",
    "A #adj# #specimen#, #verbed# with #substance#.",
    "A #adj# soul — part #animal#, part #specimen#.",
    "A #location##specimen# with a taste for #emotion#.",
    "Born #on# the #ground#, #verbed# by #substance#.",
    "This #adj# creature #transVerbSing# its #emotion# deeply.",
    "Have you seen my #substance#?",
  ],
});
//this.poem = this.ruleGrammar.flatten("#Description#");
class FishText {
  constructor() {
    this.name = FishGrammer.flatten("#fishName#");
    this.desc = FishGrammer.flatten("#Description#");
  }
  getname() {
    return this.name;
  }
  getdesc() {
    return this.desc;
  }
}
